jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: GitVersion@4
    inputs:
      updateAssemblyInfo: false   
      
  - task: NuGetToolInstaller@0
    inputs:
        versionSpec: 4.9.1
        checkLatest: false

  - task: MSBuild@1
    inputs:
      solution: src/build/build.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: MSBuild@1
    displayName: ARM Android build
    inputs:
      solution: src/CalcManager.Android/CalcManager.Android.vcxproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:Platform=ARM /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: MSBuild@1
    displayName: ARM64 Android build
    inputs:
      solution: src/CalcManager.Android/CalcManager.Android.vcxproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:Platform=ARM64 /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
      
  - task: MSBuild@1
    displayName: X86 Android build
    inputs:
      solution: src/CalcManager.Android/CalcManager.Android.vcxproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:Platform=x86 /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: MSBuild@1
    inputs:
      solution: src/Calculator.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /detailedsummary /p:AndroidSigningKeyPass=$(KeystorePassword) /p:AndroidSigningStorePass=$(KeystorePassword) 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
      
  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wasm-interp
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: CopyFiles@2
    displayName: 'Publish Android Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.Droid/bin/Release
      Contents: '**/*.apk'
      TargetFolder: $(build.artifactstagingdirectory)/android
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: CopyFiles@2
    displayName: 'Publish Windows Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.UWP/AppPackages
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/windows
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: $(build.artifactstagingdirectory)
      artifactType: container
      artifactName: Calculator
