// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace CalcManager.Interop
{
    enum UnitConverterCommand
    {
        Zero = 0,
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4,
        Five = 5,
        Six = 6,
        Seven = 7,
        Eight = 8,
        Nine = 9,
        Decimal = 10,
        Negate = 11,
        Backspace = 12,
        Clear = 13,
        Reset = 14,
        None = 15,
    };

    struct UnitWrapper
    {
        Int32 Id;
        String Name;
        String AccessibleName;
        String Abbreviation;
        Boolean IsConversionSource;
        Boolean IsConversionTarget;
        Boolean IsWhimsical;
    };

    struct CategoryWrapper
    {
        Int32 Id;
        String Name;
        Boolean SupportsNegative;
    };

    struct ConversionDataWrapper
    {
        Double Ratio;
        Double Offset;
        Boolean OffsetFirst;
    };

    struct UnitConversionEntry
    {
        UnitWrapper Unit;
        Double Ratio;
        Double Offset;
        Boolean OffsetFirst;
    };

    struct SuggestedValueWrapper
    {
        String Value;
        UnitWrapper Unit;
    };

    runtimeclass CategorySelectionResult
    {
        CategorySelectionResult();
        UnitWrapper[] Units{ get; };
        UnitWrapper FromUnit{ get; };
        UnitWrapper ToUnit{ get; };
    };

    unsealed runtimeclass UnitConverterVMCallbackBase
    {
        UnitConverterVMCallbackBase();
        overridable void DisplayCallback(String fromValue, String toValue);
        overridable void SuggestedValueCallback(SuggestedValueWrapper[] suggestedValues);
        overridable void MaxDigitsReached();
    };

    unsealed runtimeclass ViewModelCurrencyCallbackBase
    {
        ViewModelCurrencyCallbackBase();
        overridable void CurrencyDataLoadFinished(Boolean didLoad);
        overridable void CurrencySymbolsCallback(String fromSymbol, String toSymbol);
        overridable void CurrencyRatiosCallback(String ratioEquality, String accRatioEquality);
        overridable void CurrencyTimestampCallback(String timestamp, Boolean isWeekOldData);
        overridable void NetworkBehaviorChanged(Int32 newBehavior);
    };

    unsealed runtimeclass ConverterDataLoaderBase
    {
        ConverterDataLoaderBase();
        overridable void LoadData();
        overridable CategoryWrapper[] GetOrderedCategories();
        overridable UnitWrapper[] GetOrderedUnits(CategoryWrapper category);
        overridable UnitConversionEntry[] LoadOrderedRatios(UnitWrapper unit);
        overridable Boolean SupportsCategory(CategoryWrapper target);
    };

    runtimeclass UnitConverterWrapper
    {
        UnitConverterWrapper(ConverterDataLoaderBase dataLoader);
        void Initialize();
        CategoryWrapper[] GetCategories();
        CategorySelectionResult SetCurrentCategory(CategoryWrapper category);
        CategoryWrapper GetCurrentCategory();
        void SetCurrentUnitTypes(UnitWrapper fromType, UnitWrapper toType);
        void SwitchActive(String newValue);
        Boolean IsSwitchedActive{ get; };
        String SaveUserPreferences();
        void RestoreUserPreferences(String userPreference);
        void SendCommand(UnitConverterCommand command);
        void SetViewModelCallback(UnitConverterVMCallbackBase callback);
        void SetViewModelCurrencyCallback(ViewModelCurrencyCallbackBase callback);
        void Calculate();
        void ResetCategoriesAndRatios();
    };
}
