// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using CalcManager;
using CalcManager.CalculationManager;

namespace CalculatorUnitTests
{
    public class EngineResourceProvider : IResourceProvider
    {
        private static readonly Dictionary<string, string> s_strings = new Dictionary<string, string>
        {
            { "sDecimal", "." },
            { "sThousand", "," },
            { "sGrouping", "3;0" },
            { "0", "+/-" },
            { "1", "C" },
            { "2", "CE" },
            { "3", "Back" },
            { "4", "." },
            { "5", "" },
            { "6", "AND" },
            { "7", "OR" },
            { "8", "XOR" },
            { "9", "Lsh" },
            { "10", "Rsh" },
            { "11", "\u00F7" },
            { "12", "\u00D7" },
            { "13", "+" },
            { "14", "-" },
            { "15", "Mod" },
            { "16", "yroot" },
            { "17", "^" },
            { "18", "Int" },
            { "19", "RoL" },
            { "20", "RoR" },
            { "21", "NOT" },
            { "22", "sin" },
            { "23", "cis" },
            { "24", "tan" },
            { "25", "sinh" },
            { "26", "cosh" },
            { "27", "tanh" },
            { "28", "ln" },
            { "29", "log" },
            { "30", "\u221A" },
            { "31", "sqr" },
            { "32", "cube" },
            { "33", "fact" },
            { "34", "1/" },
            { "35", "dms" },
            { "37", "10^" },
            { "38", "%" },
            { "39", "F-E" },
            { "40", "Pi" },
            { "41", "=" },
            { "42", "MC" },
            { "43", "MR" },
            { "44", "MS" },
            { "45", "M+" },
            { "46", "M-" },
            { "47", "Exp" },
            { "48", "(" },
            { "49", ")" },
            { "50", "0" },
            { "51", "1" },
            { "52", "2" },
            { "53", "3" },
            { "54", "4" },
            { "55", "5" },
            { "56", "6" },
            { "57", "7" },
            { "58", "8" },
            { "59", "9" },
            { "60", "A" },
            { "61", "B" },
            { "62", "C" },
            { "63", "D" },
            { "64", "E" },
            { "65", "F" },
            { "66", "frac" },
            { "67", "sin\u2080" },
            { "68", "cos\u2080" },
            { "69", "tan\u2080" },
            { "70", "sin\u2080\u207B\u00B9" },
            { "71", "cos\u2080\u207B\u00B9" },
            { "72", "tan\u2080\u207B\u00B9" },
            { "73", "sin\u1D63" },
            { "74", "cos\u1D63" },
            { "75", "tan\u1D63" },
            { "76", "sin\u1D63\u207B\u00B9" },
            { "77", "cos\u1D63\u207B\u00B9" },
            { "78", "tan\u1D63\u207B\u00B9" },
            { "79", "sin\u1D4D" },
            { "80", "cos\u1D4D" },
            { "81", "tan\u1D4D" },
            { "82", "sin\u1D4D\u207B\u00B9" },
            { "83", "cos\u1D4D\u207B\u00B9" },
            { "84", "tan\u1D4D\u207B\u00B9" },
            { "85", "sinh\u207B\u00B9" },
            { "86", "cosh\u207B\u00B9" },
            { "87", "tanh\u207B\u00B9" },
            { "88", "e^" },
            { "89", "10^" },
            { "90", "\u221A" },
            { "91", "sqr" },
            { "92", "cube" },
            { "93", "cuberoot" },
            { "94", "fact" },
            { "95", "1/" },
            { "96", "degrees" },
            { "97", "negate" },
            { "98", "Rsh" },
            { "99", "Cannot divide by zero" },
            { "100", "Invalid input" },
            { "101", "Result is undefined" },
            { "102", "Infinity" },
            { "103", "-Infinity" },
            { "105", "Not enough memory" },
            { "107", "Overflow" },
            { "108", "Result not defined" },
            { "109", "Insufficient data" },
            { "111", "Invalid input" },
            { "118", "Result not defined" },
            { "119", "Overflow" },
            { "120", "Overflow" },
            { "SecDeg", "sec\u2080" },
            { "SecRad", "sec\u1D63" },
            { "SecGrad", "sec\u1D4D" },
            { "InverseSecDeg", "sec\u2080\u207B\u00B9" },
            { "InverseSecRad", "sec\u1D63\u207B\u00B9" },
            { "InverseSecGrad", "sec\u1D4D\u207B\u00B9" },
            { "CscDeg", "csc\u2080" },
            { "CscRad", "csc\u1D63" },
            { "CscGrad", "csc\u1D4D" },
            { "InverseCscDeg", "csc\u2080\u207B\u00B9" },
            { "InverseCscRad", "csc\u1D63\u207B\u00B9" },
            { "InverseCscGrad", "csc\u1D4D\u207B\u00B9" },
            { "CotDeg", "cot\u2080" },
            { "CotRad", "cot\u1D63" },
            { "CotGrad", "cot\u1D4D" },
            { "InverseCotDeg", "cot\u2080\u207B\u00B9" },
            { "InverseCotRad", "cot\u1D63\u207B\u00B9" },
            { "InverseCotGrad", "cot\u1D4D\u207B\u00B9" },
            { "Sech", "sech" },
            { "InverseSech", "sech\u207B\u00B9" },
            { "Csch", "csch" },
            { "InverseCsch", "csch\u207B\u00B9" },
            { "Coth", "coth" },
            { "InverseCoth", "coth\u207B\u00B9" },
            { "TwoPowX", "2^" },
            { "LogBaseY", "log base" },
            { "Abs", "abs" },
            { "Floor", "floor" },
            { "Ceil", "ceil" },
            { "Nand", "NAND" },
            { "Nor", "NOR" },
            { "CubeRoot", "cuberoot" },
            { "ProgrammerMod", "%" }
        };

        public string GetCEngineString(string id)
        {
            if (s_strings.TryGetValue(id, out var val))
            {
                return val;
            }
            return id;
        }
    }
}
