// SPDX-License-Identifier: MIT
// Copyright (c) 2026-present Tian Liao

#ifndef EPSILON_INC_R_HPP
#define EPSILON_INC_R_HPP

// std
#include <algorithm>
#include <functional>
#include <limits>

// epx
#include "coro.hpp"
#include "z.hpp"

namespace epx {

template <container C>
class r {
 public:
  template <class F>
    requires(!std::same_as<std::remove_cvref_t<F>, r>)
  explicit r(F&& x) : x_(std::forward<F>(x)) {}
  r(const r&) = default;
  r(r&&) noexcept = default;
  r& operator=(const r&) = default;
  r& operator=(r&&) noexcept = default;
  coro::lazy<z<C>> approx(int n) const {
    if (n <= mpa_) {
      co_return mul_4exp(const_cast<const z<C>&>(x_mpa_), n - mpa_);
    } else {
      mpa_ = n;
      x_mpa_ = co_await x_(n);
      co_return x_mpa_;
    }
  }

 private:
  std::function<coro::lazy<z<C>>(int)> x_;
  mutable int mpa_ = std::numeric_limits<int>::min();  // most precise approximation
  mutable z<C> x_mpa_;
};

template <container C>
constexpr r<C> make_q(z<C> p, z<C> q) {
  return r<C>{[p = std::move(p), q = std::move(q)](int n) -> coro::lazy<z<C>> {
    auto rr = mul_4exp(p, n);
    auto [quo, _] = floor_div(rr, q);
    co_return quo;  // q (n) = floor(p * 4^n / q)
  }};
}

template <container C>
constexpr r<C> add(r<C> x, r<C> y) {
  return r<C>{[x = std::move(x), y = std::move(y)](int n) -> coro::lazy<z<C>> {
    if (n == std::numeric_limits<int>::max()) [[unlikely]] {
      throw precision_overflow_error{};
    }
    // w = 4 when B = 4.
    auto xn = co_await x.approx(n + 1);
    auto yn = co_await y.approx(n + 1);
    co_return mul_4exp(xn + yn, -1);
  }};
}

template <container C>
constexpr r<C> opp(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    auto xn = co_await x.approx(n);
    negate(xn);
    co_return xn;
  }};
}

template <container C>
coro::lazy<int> msd(r<C> x, int max) {
  const auto zero = details::zero<C>();
  const auto one = details::one<C>();
  const auto base = details::base<C>();

  auto x0 = co_await x.approx(0);
  if (cmp_n(x0, base) > 0) {  // 4 < x0
    int i = -1;
    for (;;) {
      auto xi = co_await x.approx(i);
      if (cmp_n(xi, one) <= 0) {
        co_return i + 1;
      }
      --i;  // TODO: use faster search algo.
    }
  } else if (cmp_n(x0, one) > 0) {  // 1 < x0 <= 4
    co_return 0;
  } else if (cmp_n(x0, zero) > 0) {  // 0 < x0 <= 1
    co_return 1;
  } else {  // x0 <= 0
    int i = 0;
    auto xi = x0;
    for (;;) {
      auto c = cmp_n(xi, one);
      if (c > 0 || i >= max) {
        co_return i;
      }
      ++i;  // TODO: use faster search algo.
      if (i > max_msd<global_config_tag>) [[unlikely]] {
        throw msd_overflow_error{};
      }
      xi = co_await x.approx(i);
    }
  }
}

template <container C>
coro::lazy<int> msd(r<C> x) {
  return msd(std::move(x), std::numeric_limits<int>::max());
}

template <container C>
constexpr r<C> mul(r<C> x, r<C> y) {
  return r<C>{[x = std::move(x), y = std::move(y)](int n) -> coro::lazy<z<C>> {
    if (n > std::numeric_limits<int>::max() - 3) [[unlikely]] {
      throw precision_overflow_error{};
    }
    const auto one = details::one<C>();
    int max_msd = n + 3 - (n + 2) / 2;
    int px = n - (co_await msd(y, max_msd)) + 3;
    int py = n - (co_await msd(x, max_msd)) + 3;
    auto xpx = co_await x.approx(px);
    auto ypy = co_await y.approx(py);
    auto xy = mul_4exp(add_n(mul_n(xpx, ypy), one), n - px - py);
    xy.sgn = xpx.sgn == ypy.sgn ? sign::positive : sign::negative;
    co_return xy;
  }};
}

template <container C>
constexpr r<C> inv(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    int msdx = co_await msd(x);
    if (n <= -msdx) {
      co_return z<C>{};  // zero
    }

    assert(std::numeric_limits<int>::max() > 2 * max_msd<global_config_tag> + 1);
    if (n > std::numeric_limits<int>::max() - 2 * max_msd<global_config_tag> - 1) [[unlikely]] {
      throw precision_overflow_error{};
    }

    int k = n + 2 * msdx + 1;
    auto p = mul_4exp(details::one<C>(), k + n);
    auto q = add(co_await x.approx(k), details::one<C>());
    auto [quo, _] = ceil_div(p, q);
    co_return add(quo, details::one<C>());
  }};
}

template <container C>
constexpr r<C> root(r<C> x, int k) {
  return r<C>{[x = std::move(x), k](int n) -> coro::lazy<z<C>> {
    if (k < 2) [[unlikely]] {
      throw kthroot_too_small_error{};
    }

    auto xn = co_await x.approx(n * k);
    if (is_negative(xn)) [[unlikely]] {
      throw negative_radicand_error{};
    }
    co_return root(xn, k);
  }};
}

// Generated by AI — Exponential function (Section 4.3.3 of Ménissier-Morain's paper)
namespace details {

constexpr int exp_guard = 12;

// Compute floor(exp(frac / 4^k) * 4^p) via Taylor series.
// Requires: frac <= 0 and |frac| <= 4^k (i.e., frac/4^k in [-1, 0]).
template <container C>
constexpr z<C> exp_taylor(const z<C>& frac, int k, int p) {
  const int wp = p + exp_guard;
  auto sum = mul_4exp(one<C>(), wp);  // 1 * 4^wp
  auto term = sum;

  if (is_zero(frac)) {
    return mul_4exp(one<C>(), p);
  }

  auto denom = mul_4exp(one<C>(), k);  // 4^k
  for (int i = 1;; ++i) {
    // term = term * frac / (i * 4^k)  (signed: frac may be negative)
    auto i_z = create<C>(i);
    auto divisor = mul_4exp(i_z, k);
    term = mul(term, frac);
    auto [q, _] = floor_div(term, divisor);
    term = std::move(q);

    if (is_zero(term)) {
      break;
    }
    sum = add(sum, term);
  }

  // shift from wp back to p
  return mul_4exp(sum, -(exp_guard));
}

// Compute floor(e * 4^p) via Taylor series e = sum 1/k!
template <container C>
constexpr z<C> compute_e(int p) {
  const int wp = p + exp_guard;
  auto sum = mul_4exp(one<C>(), wp);  // 1 * 4^wp
  auto term = sum;

  for (int i = 1;; ++i) {
    auto [q, _] = floor_div(term, create<C>(i));
    term = std::move(q);
    if (is_zero(term)) {
      break;
    }
    sum = add_n(sum, term);
  }

  return mul_4exp(sum, -(exp_guard));
}

// Fixed-point multiply: floor(a * b / 4^prec)
template <container C>
constexpr z<C> fp_mul(const z<C>& a, const z<C>& b, int prec) {
  auto prod = mul(a, b);
  return mul_4exp(prod, -prec);
}

// Binary exponentiation in fixed-point: compute floor(base^exp * 4^prec)
// base is a fixed-point value at precision prec (i.e., represents base / 4^prec).
template <container C>
constexpr z<C> fp_pow(const z<C>& base, int exp, int prec) {
  if (exp == 0) return mul_4exp(one<C>(), prec);
  if (exp == 1) return base;

  auto result = mul_4exp(one<C>(), prec);
  auto b = base;
  int e = exp;
  while (e > 0) {
    if (e & 1) {
      result = fp_mul<C>(result, b, prec);
    }
    e >>= 1;
    if (e > 0) {
      b = fp_mul<C>(b, b, prec);
    }
  }
  return result;
}

// Compute v such that |exp(num / 4^k) - v / 4^p| < 1 / 4^p.
template <container C>
constexpr z<C> exp_rational(z<C> num, int k, int p) {
  if (is_zero(num)) {
    return mul_4exp(one<C>(), p);
  }

  // Decompose: m = floor(num / 4^k) + 1, frac = num - m * 4^k
  // so frac / 4^k is in [-1, 0).
  auto bk = mul_4exp(one<C>(), k);  // 4^k
  auto [q_div, _] = floor_div(num, bk);
  auto m = add(q_div, one<C>());     // m = floor(num/4^k) + 1  (signed)
  auto frac = sub(num, mul(m, bk));  // frac = num - m * 4^k    (signed)

  // Determine sign of m
  bool m_negative = is_negative(m);
  int m_abs_int = 0;
  {
    auto m_abs = m;
    if (m_negative) negate(m_abs);
    // Convert small z to int for exponent (m is bounded by |x| + 1)
    if (!is_zero(m_abs)) {
      // Extract value: m_abs should fit in a reasonable int
      auto m_str = is_zero(m_abs) ? std::string("0") : std::string{};
      if (m_str.empty()) {
        // Simple extraction for small values
        auto tmp = m_abs;
        while (!is_zero(tmp)) {
          auto [qt, r] = div_n(tmp, ten<C>());
          m_str.push_back(is_zero(r) ? '0' : static_cast<char>(r.digits[0]) + '0');
          tmp = std::move(qt);
        }
        std::ranges::reverse(m_str);
      }
      for (char c : m_str) {
        m_abs_int = m_abs_int * 10 + (c - '0');
      }
    }
  }

  // Extra precision for intermediate computations.
  // e^|m| has about |m| * log_4(e) base-4 digits (log_4(e) < 0.72135). The
  // fixed-point arithmetic below carries a relative error of ~4^-wp, so the
  // absolute error in the (possibly huge) value e^|m| is ~e^|m| * 4^-wp. For
  // the result to stay within 4^-p of exp(num/4^k), wp must exceed the base-4
  // magnitude of e^|m|; otherwise large exponents (e.g. pow(2, 1000)) lose the
  // low-order digits. The negative branch needs the same margin so the
  // inversion 4^(2*wp) / e^|m| keeps p significant digits.
  const int mag4 = static_cast<int>((static_cast<long long>(m_abs_int) * 72135) / 100000) + 1;
  const int extra = exp_guard + mag4 + 5;
  const int wp = p + extra;

  // Compute exp(frac / 4^k) at precision wp
  auto exp_frac = exp_taylor<C>(frac, k, wp);

  if (m_abs_int == 0) {
    // exp(num/4^k) = exp(frac/4^k)
    return mul_4exp(exp_frac, -(extra));
  }

  // Compute e at precision wp
  auto e_val = compute_e<C>(wp);

  // Compute e^|m| at precision wp using binary exponentiation
  auto e_pow = fp_pow<C>(e_val, m_abs_int, wp);

  if (m_negative) {
    // e^m = 1/e^|m|, compute as 4^(2*wp) / e_pow
    auto inv_num = mul_4exp(one<C>(), 2 * wp);
    auto [inv_q, __] = floor_div(inv_num, e_pow);
    e_pow = std::move(inv_q);
  }

  // result = exp_frac * e_pow / 4^wp (fixed-point multiply)
  auto result = fp_mul<C>(exp_frac, e_pow, wp);

  // shift from wp to p
  return mul_4exp(result, -(extra));
}

// Compute floor(log_e(1 + 1/4^n) * 4^prec).
// log(1 + z) = z - z^2/2 + z^3/3 - ...  for z = 1/4^n.
template <container C>
constexpr z<C> log_near_one_plus(int n, int prec) {
  if (prec < 0) {
    // For non-positive precision, log(1 + 1/4^n) < 1/4^n < 1
    // so floor(log(1+1/4^n) * 4^prec) = 0
    return zero<C>();
  }
  const int wp = prec + exp_guard;
  // z = 1/4^n, in fixed-point at wp: z_fp = 4^(wp-n)
  if (wp < n) return zero<C>();

  auto sum = mul_4exp(one<C>(), wp - n);  // z * 4^wp = 4^(wp-n)
  auto z_pow = sum;                       // z^1 in fixed-point
  auto z_fp = sum;                        // z in fixed-point

  for (int i = 2;; ++i) {
    // z_pow = z_pow * z / 4^wp (but z = 1/4^n, so z_pow * 1/4^n)
    z_pow = mul_4exp(z_pow, -n);
    if (is_zero(z_pow)) break;

    auto [term, _] = floor_div(z_pow, create<C>(i));
    if (is_zero(term)) break;

    if (i % 2 == 0) {
      sum = sub(sum, term);  // even terms are subtracted
    } else {
      sum = add(sum, term);  // odd terms are added
    }
  }

  return mul_4exp(sum, -(exp_guard));
}

// Compute floor(log_e(1 - 1/4^n) * 4^prec).
// log(1 - z) = -z - z^2/2 - z^3/3 - ...  for z = 1/4^n.
// Result is negative.
template <container C>
constexpr z<C> log_near_one_minus(int n, int prec) {
  if (prec < 0) {
    // log(1 - 1/4^n) is in (-1, 0) for n >= 1
    // floor(log(1-1/4^n) * 4^prec) = -1 or 0
    return zero<C>();
  }
  const int wp = prec + exp_guard;
  if (wp < n) {
    // The leading term -1/4^n * 4^wp = -4^(wp-n) which is 0 when wp < n
    auto r = create<C>(-1);
    return r;
  }

  // All terms are negative: -z - z^2/2 - z^3/3 - ...
  auto sum = zero<C>();
  auto z_pow = mul_4exp(one<C>(), wp - n);  // z^1 in fixed-point

  for (int i = 1;; ++i) {
    if (is_zero(z_pow)) break;
    auto [term, _] = floor_div(z_pow, create<C>(i));
    if (is_zero(term)) break;

    sum = add_n(sum, term);  // accumulate |terms|

    // z_pow *= z = z_pow / 4^n
    z_pow = mul_4exp(z_pow, -n);
  }

  // result is -sum
  negate(sum);
  return mul_4exp(sum, -(exp_guard));
}

// Compute d = max(-p, ceil(c * log_4(e) * 4^(-msd_x)))
// Uses upper bound: log_4(e) < 72135/100000
template <container C>
constexpr int compute_d(int c, int msd_x, int p) {
  // c * log_4(e) * 4^(-msd_x)
  // For msd_x >= 0: 4^(-msd_x) <= 1, result is small
  // For msd_x < 0: 4^(-msd_x) = 4^|msd_x|, result can be large
  //
  // We compute: ceil(c * 72135 / 100000 * 4^(-msd_x))
  // = ceil(c * 72135 * 4^(-msd_x) / 100000)

  // Use big integers to avoid overflow
  auto c_z = create<C>(c);
  auto num = mul_n(c_z, create<C>(72135));  // c * 72135
  if (-msd_x > 0) {
    mul_4exp(num, -msd_x);  // * 4^(-msd_x)
  } else if (-msd_x < 0) {
    // 4^(-msd_x) = 4^(msd_x is positive) => this means divide
    // Actually: 4^(-msd_x) where msd_x > 0 means divide by 4^msd_x
    mul_4exp(num, -msd_x);  // -msd_x < 0 here, so this divides
  }

  auto denom = create<C>(100000);
  auto [q, r] = floor_div(num, denom);
  int d_val = 0;
  if (!is_zero(r)) {
    q = add_n(q, one<C>());  // ceil
  }

  // Convert q to int
  if (!is_zero(q)) {
    auto tmp = q;
    tmp.sgn = sign::positive;
    std::string s;
    while (!is_zero(tmp)) {
      auto [qt, rm] = div_n(tmp, ten<C>());
      s.push_back(is_zero(rm) ? '0' : static_cast<char>(rm.digits[0]) + '0');
      tmp = std::move(qt);
    }
    std::ranges::reverse(s);
    for (char ch : s) d_val = d_val * 10 + (ch - '0');
  }

  return std::max(-p, d_val);
}

// Compute k = max(0, msd_x, p + 1 + ceil(d + log_4((e+1)/2)))
// Uses upper bound: log_4((e+1)/2) < 44732/100000 < 1
// So ceil(d + 0.44732) = d + 1 for non-negative integer d.
constexpr int compute_k(int msd_x, int p, int d) {
  int k_candidate = p + 1 + d + 1;  // ceil(d + 0.44732) = d + 1
  return std::max({0, msd_x, k_candidate});
}

constexpr int log_guard = 12;

// Compute floor(ln(2) * 4^prec) via arctanh(1/3): ln(2) = 2 * arctanh(1/3)
template <container C>
constexpr z<C> compute_ln2(int prec) {
  if (prec < 0) return zero<C>();
  const int wp = prec + log_guard;
  auto [z_fp, _] = floor_div(mul_4exp(one<C>(), wp), create<C>(3));
  if (is_zero(z_fp)) return zero<C>();
  auto z2 = fp_mul<C>(z_fp, z_fp, wp);
  auto sum = z_fp;
  auto z_pow = z_fp;
  for (int i = 1;; ++i) {
    z_pow = fp_mul<C>(z_pow, z2, wp);
    if (is_zero(z_pow)) break;
    auto denom = create<C>(2 * i + 1);
    auto [term, _2] = floor_div(z_pow, denom);
    if (is_zero(term)) break;
    sum = add_n(sum, term);
  }
  mul_2exp(sum, 1);
  return mul_4exp(sum, -(log_guard));
}

// Compute floor(ln(num / 4^k) * 4^p) for positive rational num/4^k.
// Uses ln(r) = 2*arctanh((r-1)/(r+1)) for r > 1 (Section 4.5.3),
// and ln(r) = -ln(1/r) for r < 1.
// For large r, decomposes r = 4^m * r' with r' in [1, 4).
template <container C>
constexpr z<C> log_rational(z<C> num, int k, int p) {
  if (is_zero(num) || is_negative(num)) {
    throw non_positive_log_error{};
  }

  auto bk = mul_4exp(one<C>(), k);
  int rel = cmp_n(num, bk);
  if (rel == 0) return zero<C>();

  if (rel < 0) {
    // r < 1: ln(r) = -ln(1/r), represent 1/r = 4^k/num at precision inv_k
    const int inv_k = p + log_guard;
    auto inv_numer = mul_4exp(one<C>(), inv_k + k);
    auto [inv_num, _] = floor_div(inv_numer, num);
    auto result = log_rational<C>(std::move(inv_num), inv_k, p);
    negate(result);
    return result;
  }

  // r = num / 4^k > 1
  // Decompose r = 4^m * r' where r' in [1, 4) for faster arctanh convergence
  int m = 0;
  {
    int bl = bit_length(num.digits);
    m = std::max(0, (bl - 1) / 2 - k);
    // Adjust m upward if num >= 4^(k+m+1)
    auto upper = mul_4exp(one<C>(), k + m + 1);
    while (cmp_n(num, upper) >= 0) {
      ++m;
      upper = mul_4exp(one<C>(), k + m + 1);
    }
    // Adjust m downward if num < 4^(k+m)
    if (m > 0) {
      auto lower = mul_4exp(one<C>(), k + m);
      while (cmp_n(num, lower) < 0 && m > 0) {
        --m;
        lower = mul_4exp(one<C>(), k + m);
      }
    }
  }

  const int wp = p + log_guard;

  // Compute ln(r') = 2 * arctanh(y), y = (num - 4^(k+m)) / (num + 4^(k+m))
  auto bk_m = mul_4exp(one<C>(), k + m);
  auto nm = sub(num, bk_m);
  auto np = add_n(num, bk_m);

  z<C> ln_rprime;
  if (is_zero(nm)) {
    ln_rprime = zero<C>();
  } else {
    auto y_num = mul_4exp(nm, wp);
    auto [y_fp, _2] = floor_div(y_num, np);
    auto y2 = fp_mul<C>(y_fp, y_fp, wp);
    auto sum = y_fp;
    auto y_pow = y_fp;
    for (int i = 1;; ++i) {
      y_pow = fp_mul<C>(y_pow, y2, wp);
      if (is_zero(y_pow)) break;
      auto [term, _3] = floor_div(y_pow, create<C>(2 * i + 1));
      if (is_zero(term)) break;
      sum = add_n(sum, term);
    }
    ln_rprime = sum;
    mul_2exp(ln_rprime, 1);
  }

  if (m == 0) {
    return mul_4exp(ln_rprime, -(log_guard));
  }

  // ln(r) = 2m * ln(2) + ln(r')
  auto ln2_val = compute_ln2<C>(wp);
  auto m_contrib = mul(create<C>(2 * m), ln2_val);
  auto result = add(m_contrib, ln_rprime);
  return mul_4exp(result, -(log_guard));
}

constexpr int atan_guard = 12;

// Compute floor(arctan(1/n) * 4^prec) via alternating Taylor series:
// arctan(1/n) = 1/n - 1/(3n^3) + 1/(5n^5) - ...
// Convergence ratio 1/n^2; fast for n >= 2.
template <container C>
constexpr z<C> atan_reciprocal(int n, int prec) {
  if (prec < 0) return zero<C>();
  const int wp = prec + atan_guard;
  auto n2 = create<C>(static_cast<long long>(n) * n);
  auto [power, _] = floor_div(mul_4exp(one<C>(), wp), create<C>(n));
  if (is_zero(power)) return zero<C>();
  auto sum = power;
  for (int i = 1;; ++i) {
    auto [q, _2] = floor_div(power, n2);
    power = std::move(q);
    if (is_zero(power)) break;
    auto [term, _3] = floor_div(power, create<C>(2 * i + 1));
    if (is_zero(term)) break;
    if (i % 2 == 1)
      sum = sub(sum, term);
    else
      sum = add_n(sum, term);
  }
  return mul_4exp(sum, -(atan_guard));
}

// Compute floor(pi * 4^prec) via Gauss's formula:
// pi/4 = 12*arctan(1/18) + 8*arctan(1/57) - 5*arctan(1/239)
template <container C>
constexpr z<C> compute_pi(int prec) {
  if (prec < 0) return zero<C>();
  const int wp = prec + atan_guard;
  auto a = atan_reciprocal<C>(18, wp);
  auto b = atan_reciprocal<C>(57, wp);
  auto c = atan_reciprocal<C>(239, wp);
  auto sum = sub(add(mul(create<C>(12), a), mul(create<C>(8), b)), mul(create<C>(5), c));
  mul_4exp(sum, 1);  // multiply by 4: pi = 4 * (pi/4)
  return mul_4exp(sum, -(atan_guard));
}

// Compute arctan(a/b) * 4^prec for a >= 0, b > 0 using direct Taylor series.
// Requires 0 < a/b <= 1/2 for fast convergence (ratio y^2 <= 1/4).
template <container C>
constexpr z<C> atan_series(const z<C>& a, const z<C>& b, int prec) {
  auto [y_fp, _] = floor_div(mul_4exp(a, prec), b);
  if (is_zero(y_fp)) return zero<C>();
  auto y2 = fp_mul<C>(y_fp, y_fp, prec);
  auto sum = y_fp;
  auto y_pow = y_fp;
  for (int i = 1;; ++i) {
    y_pow = fp_mul<C>(y_pow, y2, prec);
    if (is_zero(y_pow)) break;
    auto [term, _2] = floor_div(y_pow, create<C>(2 * i + 1));
    if (is_zero(term)) break;
    if (i % 2 == 1)
      sum = sub(sum, term);
    else
      sum = add_n(sum, term);
  }
  return sum;
}

// Compute approximately arctan(num/4^k) * 4^p (within +/- 1).
// Uses argument reduction for fast convergence:
//   |y| > 1:   arctan(y) = pi/2 - arctan(1/y)
//   |y| > 1/2: arctan(y) = pi/4 + arctan((y-1)/(y+1))
//   |y| <= 1/2: direct Taylor series
template <container C>
constexpr z<C> atan_rational(z<C> num, int k, int p) {
  if (is_zero(num)) return zero<C>();

  const int wp = p + atan_guard;
  if (wp < 0) return zero<C>();

  const bool neg = is_negative(num);
  if (neg) negate(num);

  auto denom = mul_4exp(one<C>(), k);
  z<C> result;
  int rel = cmp_n(num, denom);

  if (rel > 0) {
    // |y| > 1: arctan(|y|) = pi/2 - arctan(denom/num)
    auto two_denom = mul_4exp(denom, 0);
    mul_2exp(two_denom, 1);
    if (cmp_n(two_denom, num) > 0) {
      // denom/num > 1/2: arctan(|y|) = pi/4 + arctan((num-denom)/(num+denom))
      auto [pq, _] = floor_div(compute_pi<C>(wp), create<C>(4));
      result = add(pq, atan_series<C>(sub(num, denom), add_n(num, denom), wp));
    } else {
      // denom/num <= 1/2: arctan(|y|) = pi/2 - arctan_series(denom, num)
      auto [ph, _] = floor_div(compute_pi<C>(wp), create<C>(2));
      result = sub(ph, atan_series<C>(denom, num, wp));
    }
  } else if (rel == 0) {
    // |y| = 1: arctan(1) = pi/4
    auto [pq, _] = floor_div(compute_pi<C>(wp), create<C>(4));
    result = pq;
  } else {
    // |y| < 1
    auto two_num = mul_4exp(num, 0);
    mul_2exp(two_num, 1);
    if (cmp_n(two_num, denom) > 0) {
      // |y| > 1/2: arctan(|y|) = pi/4 - arctan((denom-num)/(denom+num))
      auto [pq, _] = floor_div(compute_pi<C>(wp), create<C>(4));
      result = sub(pq, atan_series<C>(sub(denom, num), add_n(denom, num), wp));
    } else {
      // |y| <= 1/2: direct series
      result = atan_series<C>(num, denom, wp);
    }
  }

  if (neg) negate(result);
  return mul_4exp(result, -(atan_guard));
}

constexpr int sin_guard = 12;

// Compute floor(sin(num/4^k) * 4^prec) via Taylor series:
// sin(y) = y - y^3/3! + y^5/5! - y^7/7! + ...
// Requires |num/4^k| <= pi/2 for convergence guarantees.
template <container C>
constexpr z<C> sin_series(const z<C>& num, int k, int prec) {
  if (prec < 0) return zero<C>();
  const int wp = prec + sin_guard;
  auto [y_fp, _] = floor_div(mul_4exp(num, wp), mul_4exp(one<C>(), k));
  if (is_zero(y_fp)) return zero<C>();
  auto y2 = fp_mul<C>(y_fp, y_fp, wp);
  auto sum = y_fp;
  auto term = y_fp;
  for (int i = 1;; ++i) {
    term = fp_mul<C>(term, y2, wp);
    auto [q, _2] = floor_div(term, create<C>(static_cast<long long>(2 * i) * (2 * i + 1)));
    term = q;
    if (is_zero(term)) break;
    if (i % 2 == 1)
      sum = sub(sum, term);
    else
      sum = add_n(sum, term);
  }
  return mul_4exp(sum, -sin_guard);
}

}  // namespace details

// Generated by AI
template <container C>
constexpr r<C> exp(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    constexpr int w = 1;             // B = 4
    const int ell = n + w;           // l = n + 1
    const int p = std::max(0, ell);  // p = max(0, l)

    // --- Test 1: very negative x -> exp(x) ~ 0 ---
    // m = 0 for B = 4 (since ceil(log_4(e/3)) = 0)
    auto x0 = co_await x.approx(0);
    auto exp_x0_p = details::exp_rational<C>(x0, 0, p);
    if (is_zero(exp_x0_p) || is_negative(exp_x0_p)) {
      co_return z<C>{};  // zero
    }

    // --- Test 2: x near zero -> exp(x) ~ 1 ---
    // Use signed comparison via sub (cmp_n is unsigned magnitude only)
    if (n > 0) {
      auto x_ell = co_await x.approx(ell);
      auto log_lo = details::log_near_one_minus<C>(n, ell);
      auto log_hi = details::log_near_one_plus<C>(n, ell);
      auto lo_bound = add(log_lo, create<C>(2));
      auto hi_bound = sub(log_hi, create<C>(2));
      auto diff_lo = sub(x_ell, lo_bound);
      auto diff_hi = sub(x_ell, hi_bound);
      bool x_gt_lo = !is_zero(diff_lo) && !is_negative(diff_lo);
      bool x_lt_hi = is_negative(diff_hi);
      if (x_gt_lo && x_lt_hi) {
        co_return mul_4exp(details::one<C>(), n);
      }
    } else {
      // For n <= 0, compute bound = floor(log_e(1 + 4^(-n))) - 1 directly.
      // Avoids Taylor series for log which loops when n = 0.
      auto x0_val = co_await x.approx(0);
      int neg_n = -n;  // >= 0
      int log_floor;
      if (neg_n == 0) {
        log_floor = 0;  // floor(ln(2)) = 0
      } else {
        // log(1 + 4^k) > k*ln(4) > k * 1.386294 (lower bound)
        log_floor = static_cast<int>(static_cast<long long>(neg_n) * 1386294LL / 1000000LL);
      }
      int bound = log_floor - 1;
      auto bound_z = create<C>(bound);
      auto diff = sub(x0_val, bound_z);
      bool x_le_bound = is_zero(diff) || is_negative(diff);
      if (x_le_bound) {
        co_return mul_4exp(details::one<C>(), n);
      }
    }

    // --- General case ---
    // Use bounded msd: if x is very close to 0 (or exactly 0),
    // msd hits the limit and we return 4^n since exp(x) ≈ 1.
    int msd_limit = std::max(p + 10, 100);
    int msd_x = co_await msd(x, msd_limit);
    if (msd_x >= msd_limit) {
      co_return mul_4exp(details::one<C>(), n);
    }
    auto x_msd = co_await x.approx(msd_x);
    auto x_msd_abs = x_msd;
    x_msd_abs.sgn = sign::positive;
    int c = (cmp_n(x_msd_abs, details::one<C>()) >= 0) ? 8 : 1;  // 2B = 8
    int d = details::compute_d<C>(c, msd_x, p);
    int k = details::compute_k(msd_x, p, d);

    auto x_k = co_await x.approx(k);
    auto v = details::exp_rational<C>(x_k, k, p);
    co_return mul_4exp(v, n - p);
  }};
}

// Generated by AI — Natural logarithm (Algorithm 8 of Ménissier-Morain's paper)
template <container C>
constexpr r<C> log(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    constexpr int c = 2;         // B = 4 >= 3
    int w = c - std::min(0, n);  // w = c - min(0, n)

    int msd_x = co_await msd(x);
    int k = n + msd_x + w;

    auto xk = co_await x.approx(k);

    // v = floor(ln(xk / 4^k) * 4^(n+w))
    auto v = details::log_rational<C>(xk, k, n + w);

    // Result = floor((v + 1) / 4^w + 4^n / xk)
    //        = floor(((v + 1) * xk + 4^(n+w)) / (xk * 4^w))
    auto v_plus_1 = add(v, details::one<C>());
    auto numerator = add(mul(v_plus_1, xk), mul_4exp(details::one<C>(), n + w));
    auto denominator = xk;
    mul_4exp(denominator, w);
    auto [result, _] = floor_div(std::move(numerator), std::move(denominator));

    co_return result;
  }};
}

// Generated by AI — Arctangent (Algorithm 9 of Ménissier-Morain's paper)
template <container C>
constexpr r<C> arctan(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    constexpr int w = 1;  // B = 4 >= 4
    int k = std::max(0, n + w);

    auto xk = co_await x.approx(k);

    if (is_zero(xk)) {
      co_return z<C>{};  // zero
    }

    // v = approximately arctan(xk / 4^k) * 4^(n+w) (within +/- 1)
    auto v = details::atan_rational<C>(xk, k, n + w);

    // Result = floor((v + 1) / 4^w + 4^(n+k) / (4^(2n+2) + xk^2 + xk))
    // Use common-denominator integer arithmetic.
    // shift = max(0, -(2n+2)) to keep all exponents non-negative.
    int e = 2 * n + 2;
    int shift = std::max(0, -e);
    int e_pos = std::max(0, e);  // max(0, 2n+2)

    auto xk_sq = mul(xk, xk);
    auto xk_sq_plus_xk = add(xk_sq, xk);
    auto d_int = add(mul_4exp(details::one<C>(), e_pos), mul_4exp(xk_sq_plus_xk, shift));

    auto v_plus_1 = add(v, details::one<C>());
    auto numerator = add(mul(v_plus_1, d_int), mul_4exp(details::one<C>(), w + n + k + shift));
    auto denominator = d_int;
    mul_4exp(denominator, w);
    auto [result, _] = floor_div(std::move(numerator), std::move(denominator));

    co_return result;
  }};
}

// Generated by AI — Sine function (Algorithm 10 of Ménissier-Morain's paper)
// Uses 5-case classification on the trigonometric circle.
// Notation: pi_k = floor((pi/2) * 4^k), z_k = rho_k (reduced argument).
//
// From HAL p44, the 5 cases after argument reduction (rho = x - p*pi):
//   Case 1 (zones 1,5):  sin ~ 0    when |zk| or |zk - 2*pi_k| is small
//   Case 2 (zones 2,4):  sin via +series (increasing/decreasing positive)
//   Case 3 (zone 3):     sin ~ 1    when zk ~ pi_k
//   Case 4 (zones 6,8):  sin via -series (decreasing/increasing negative)
//   Case 5 (zone 7):     sin ~ -1   when zk ~ 3*pi_k
//
// With k = max(c, n+w), (c,w) = (2,2) for B=4.
template <container C>
constexpr r<C> sin(r<C> x) {
  return r<C>{[x = std::move(x)](int n) -> coro::lazy<z<C>> {
    constexpr int c = 2;  // B = 4 >= 3
    constexpr int w = 2;  // B = 4 >= 3
    const int k = std::max(c, n + w);

    auto xk = co_await x.approx(k);

    // Compute pi_full = floor(pi * 4^k), pi_k = floor((pi/2) * 4^k)
    auto pi_full = details::compute_pi<C>(k);
    if (is_zero(pi_full)) {
      co_return z<C>{};
    }
    auto two = create<C>(2);
    auto [pi_k, _s1] = floor_div(pi_full, two);

    // Argument reduction: p = floor(x_k / pi_full), zk = x_k - p * pi_full
    // sin(x) = (-1)^p * sin(zk / 4^k)   where zk is in [0, pi*4^k)
    auto [p_val, _s2] = floor_div(xk, pi_full);
    auto zk = sub(xk, mul(p_val, pi_full));

    // Determine (-1)^p sign
    bool p_odd = false;
    {
      auto p_abs = p_val;
      if (is_negative(p_abs)) negate(p_abs);
      auto [_s3, p_rem] = floor_div(p_abs, create<C>(2));
      p_odd = !is_zero(p_rem);
    }

    // Zone boundaries (multiples of pi_k = floor((pi/2) * 4^k)):
    // 0, pi_k, 2*pi_k (=pi*4^k), 3*pi_k, 4*pi_k (=2*pi*4^k)
    auto two_pi_k = mul(create<C>(2), pi_k);
    auto three_pi_k = mul(create<C>(3), pi_k);
    auto four_pi_k = mul(create<C>(4), pi_k);

    z<C> result;

    // Paper's 5-case classification (HAL p44):
    // Case 1: zk - 4*pi_k >= -4  AND  zk + 4*pi_k <= 4
    //      OR 2*pi_k - 2 <= zk  AND  zk <= 2*pi_k + 2
    //      => sin = 0
    //
    // Interpretation: zk near 0 (or near 4*pi_k = 2*pi)
    //              OR zk near 2*pi_k (= pi, where sin = 0 too)
    //
    // Case 2: -2*pi_k <= zk - 2  OR  zk + 2 <= 2*pi_k - 3
    //      => sin = (-1)^p * floor((sin_series(zk) + 1) / B^w + B^{n-k})
    //
    // Interpretation: zk in (0, pi_k) or (pi_k, 2*pi_k) — sin positive
    //
    // Case 3: zk - 1 <= pi_k <= zk + 1
    //      => sin = (-1)^p * B^n
    //
    // Interpretation: zk ~ pi_k — sin ~ 1
    //
    // Case 4: 2*zk + 3 <= 3*pi_k - 4  OR  3*zk + 4 <= 4*pi_k - 5
    //      => sin = (-1)^p * floor((-sin_series(zk) - 1) / B^w - B^{n-k})
    //
    // Interpretation: zk in (2*pi_k, 3*pi_k) or (3*pi_k, 4*pi_k) — sin negative
    //
    // Case 5: 3*pi_k - 3 <= zk <= 3*pi_k + 3
    //      => sin = (-1)^{p+1} * B^n
    //
    // Interpretation: zk ~ 3*pi_k — sin ~ -1

    // Simplified zone tests using comparisons:
    // Zone 1/5: |zk| <= 4  OR  |zk - 2*pi_k| <= 2  OR  |zk - 4*pi_k| <= 4
    // Zone 3:   |zk - pi_k| <= 1
    // Zone 7:   |zk - 3*pi_k| <= 3
    // Zone 2/4: 4 < zk < 2*pi_k - 2  (sin positive region)
    // Zone 6/8: 2*pi_k + 2 < zk < 4*pi_k - 4  (sin negative region)

    // Compute differences for zone tests
    auto diff_0 = zk;
    auto diff_pik = sub(zk, pi_k);
    auto diff_2pik = sub(zk, two_pi_k);
    auto diff_3pik = sub(zk, three_pi_k);

    auto abs_diff_0 = diff_0;
    if (is_negative(abs_diff_0)) negate(abs_diff_0);
    auto abs_diff_pik = diff_pik;
    if (is_negative(abs_diff_pik)) negate(abs_diff_pik);
    auto abs_diff_2pik = diff_2pik;
    if (is_negative(abs_diff_2pik)) negate(abs_diff_2pik);
    auto abs_diff_3pik = diff_3pik;
    if (is_negative(abs_diff_3pik)) negate(abs_diff_3pik);

    bool zone_0 = cmp_n(abs_diff_0, create<C>(4)) <= 0;
    bool zone_pik = cmp_n(abs_diff_pik, create<C>(1)) <= 0;
    bool zone_2pik = cmp_n(abs_diff_2pik, create<C>(2)) <= 0;
    bool zone_3pik = cmp_n(abs_diff_3pik, create<C>(3)) <= 0;

    if (zone_0 || zone_2pik) {
      // Case 1: sin ~ 0
      result = z<C>{};
    } else if (zone_pik) {
      // Case 3: sin ~ 1
      result = mul_4exp(details::one<C>(), n);
    } else if (zone_3pik) {
      // Case 5: sin ~ -1
      result = mul_4exp(details::one<C>(), n);
      negate(result);
    } else if (cmp_n(zk, two_pi_k) < 0) {
      // Case 2: sin positive — zk is between 0 and pi (= 2*pi_k)
      // Reduce to [0, pi/2]: if zk > pi_k, use sin(pi - arg) = sin(arg)
      z<C> arg = (cmp_n(zk, pi_k) > 0) ? sub(two_pi_k, zk) : zk;
      auto v = details::sin_series<C>(arg, k, n + w);
      auto v_plus_1 = add(v, details::one<C>());
      auto [q, _s4] = floor_div(v_plus_1, mul_4exp(details::one<C>(), w));
      result = add(q, mul_4exp(details::one<C>(), n - k));
    } else {
      // Case 4: sin negative — zk is between pi and 2*pi (= 2*pi_k to 4*pi_k)
      // sin(arg) = -sin(arg - pi)
      z<C> shifted = sub(zk, two_pi_k);
      // Now shifted is in (0, 2*pi_k), compute sin of it
      z<C> arg = (cmp_n(shifted, pi_k) > 0) ? sub(two_pi_k, shifted) : shifted;
      auto v = details::sin_series<C>(arg, k, n + w);
      auto v_minus_1 = sub(v, details::one<C>());
      auto [q, _s5] = floor_div(v_minus_1, mul_4exp(details::one<C>(), w));
      result = sub(q, mul_4exp(details::one<C>(), n - k));
      negate(result);
    }

    // Apply (-1)^p sign
    if (p_odd) negate(result);

    co_return result;
  }};
}

// Generated by AI — Cosine function: cos(x) = sin(pi/2 - x)
template <container C>
constexpr r<C> cos(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto two = make_q(create<C>(2), details::one<C>());
  auto half_pi = mul(two, arctan(one));
  return sin(add(half_pi, opp(std::move(x))));
}

// Generated by AI — Section 4.3.7: Other elementary functions
// All derived from existing primitives (exp, log, sin, cos, arctan, etc.)

// tan(x) = sin(x) / cos(x)
template <container C>
constexpr r<C> tan(r<C> x) {
  auto s = sin(x);
  auto c = cos(std::move(x));
  return mul(std::move(s), inv(std::move(c)));
}

// arcsin(x) = 2 * arctan(x / (1 + sqrt(1 - x^2))),  |x| <= 1
// Uses the half-angle identity to avoid division by zero at |x| = 1.
template <container C>
constexpr r<C> arcsin(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto two = make_q(create<C>(2), details::one<C>());
  auto x2 = mul(x, x);
  auto sqrt_term = root(add(one, opp(std::move(x2))), 2);   // sqrt(1 - x^2)
  auto denom = add(one, std::move(sqrt_term));                // 1 + sqrt(1 - x^2)
  return mul(two, arctan(mul(std::move(x), inv(std::move(denom)))));  // 2 * arctan(x / (1 + ...))
}

// arccos(x) = pi/2 - arcsin(x)
template <container C>
constexpr r<C> arccos(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto two = make_q(create<C>(2), details::one<C>());
  auto half_pi = mul(two, arctan(one));  // pi/2
  return add(std::move(half_pi), opp(arcsin(std::move(x))));
}

// sinh(x) = (exp(x) - exp(-x)) / 2
template <container C>
constexpr r<C> sinh(r<C> x) {
  auto ep = exp(x);
  auto en = exp(opp(std::move(x)));
  auto diff = add(std::move(ep), opp(std::move(en)));
  auto half = make_q(details::one<C>(), create<C>(2));
  return mul(std::move(diff), std::move(half));
}

// cosh(x) = (exp(x) + exp(-x)) / 2
template <container C>
constexpr r<C> cosh(r<C> x) {
  auto ep = exp(x);
  auto en = exp(opp(std::move(x)));
  auto sum = add(std::move(ep), std::move(en));
  auto half = make_q(details::one<C>(), create<C>(2));
  return mul(std::move(sum), std::move(half));
}

// tanh(x) = sinh(x) / cosh(x)
template <container C>
constexpr r<C> tanh(r<C> x) {
  auto s = sinh(x);
  auto c = cosh(std::move(x));
  return mul(std::move(s), inv(std::move(c)));
}

// arcsinh(x) = log(x + sqrt(x^2 + 1))
template <container C>
constexpr r<C> arcsinh(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto x2 = mul(x, x);
  auto inner = root(add(std::move(x2), std::move(one)), 2);
  return log(add(std::move(x), std::move(inner)));
}

// arccosh(x) = log(x + sqrt(x^2 - 1)),  x >= 1
template <container C>
constexpr r<C> arccosh(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto x2 = mul(x, x);
  auto inner = root(add(std::move(x2), opp(std::move(one))), 2);
  return log(add(std::move(x), std::move(inner)));
}

// arctanh(x) = (1/2) * log((1 + x) / (1 - x)),  |x| < 1
template <container C>
constexpr r<C> arctanh(r<C> x) {
  auto one = make_q(details::one<C>(), details::one<C>());
  auto numer = add(one, x);
  auto denom = add(one, opp(std::move(x)));
  auto ratio = mul(std::move(numer), inv(std::move(denom)));
  auto half = make_q(details::one<C>(), create<C>(2));
  return mul(std::move(half), log(std::move(ratio)));
}

// pow(x, y) = exp(y * log(x)),  x > 0
template <container C>
constexpr r<C> pow(r<C> x, r<C> y) {
  return exp(mul(std::move(y), log(std::move(x))));
}

// log_base(x, b) = log(x) / log(b)
template <container C>
constexpr r<C> log_base(r<C> x, r<C> b) {
  return mul(log(std::move(x)), inv(log(std::move(b))));
}

}  // namespace epx

#endif  // EPSILON_INC_R_HPP
