// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_num_one = { 1,
                                     1,
                                     0,
                                     {
                                         1,
                                     } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_num_two = { 1,
                                     1,
                                     0,
                                     {
                                         2,
                                     } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_num_five = { 1,
                                      1,
                                      0,
                                      {
                                          5,
                                      } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_num_six = { 1,
                                     1,
                                     0,
                                     {
                                         6,
                                     } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_num_ten = { 1,
                                     1,
                                     0,
                                     {
                                         10,
                                     } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_smallest = { 1,
                                            1,
                                            0,
                                            {
                                                1,
                                            } };
inline const NUMBER init_q_rat_smallest = { 1,
                                            4,
                                            0,
                                            {
                                                0,
                                                190439170,
                                                901055854,
                                                10097,
                                            } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_negsmallest = { -1,
                                               1,
                                               0,
                                               {
                                                   1,
                                               } };
inline const NUMBER init_q_rat_negsmallest = { 1,
                                               4,
                                               0,
                                               {
                                                   0,
                                                   190439170,
                                                   901055854,
                                                   10097,
                                               } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_pt_eight_five = { 1,
                                             1,
                                             0,
                                             {
                                                 85,
                                             } };
inline const NUMBER init_q_pt_eight_five = { 1,
                                             1,
                                             0,
                                             {
                                                 100,
                                             } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_six = { 1,
                                       1,
                                       0,
                                       {
                                           6,
                                       } };
inline const NUMBER init_q_rat_six = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_two = { 1,
                                       1,
                                       0,
                                       {
                                           2,
                                       } };
inline const NUMBER init_q_rat_two = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_zero = { 1,
                                        1,
                                        0,
                                        {
                                            0,
                                        } };
inline const NUMBER init_q_rat_zero = { 1,
                                        1,
                                        0,
                                        {
                                            1,
                                        } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_one = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
inline const NUMBER init_q_rat_one = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_neg_one = { -1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };
inline const NUMBER init_q_rat_neg_one = { 1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_half = { 1,
                                        1,
                                        0,
                                        {
                                            1,
                                        } };
inline const NUMBER init_q_rat_half = { 1,
                                        1,
                                        0,
                                        {
                                            2,
                                        } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_ten = { 1,
                                       1,
                                       0,
                                       {
                                           10,
                                       } };
inline const NUMBER init_q_rat_ten = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_pi = { 1,
                                  6,
                                  0,
                                  {
                                      125527896,
                                      283898350,
                                      1960493936,
                                      1672850762,
                                      1288168272,
                                      8,
                                  } };
inline const NUMBER init_q_pi = { 1,
                                  6,
                                  0,
                                  {
                                      1288380402,
                                      1120116153,
                                      1860424692,
                                      1944118326,
                                      1583591604,
                                      2,
                                  } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_two_pi = { 1,
                                      6,
                                      0,
                                      {
                                          251055792,
                                          567796700,
                                          1773504224,
                                          1198217877,
                                          428852897,
                                          17,
                                      } };
inline const NUMBER init_q_two_pi = { 1,
                                      6,
                                      0,
                                      {
                                          1288380402,
                                          1120116153,
                                          1860424692,
                                          1944118326,
                                          1583591604,
                                          2,
                                      } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_pi_over_two = { 1,
                                           6,
                                           0,
                                           {
                                               125527896,
                                               283898350,
                                               1960493936,
                                               1672850762,
                                               1288168272,
                                               8,
                                           } };
inline const NUMBER init_q_pi_over_two = { 1,
                                           6,
                                           0,
                                           {
                                               429277156,
                                               92748659,
                                               1573365737,
                                               1740753005,
                                               1019699561,
                                               5,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_one_pt_five_pi = { 1,
                                              6,
                                              0,
                                              {
                                                  1241201312,
                                                  270061909,
                                                  1051574664,
                                                  1924965045,
                                                  1340320627,
                                                  70,
                                              } };
inline const NUMBER init_q_one_pt_five_pi = { 1,
                                              6,
                                              0,
                                              {
                                                  1579671539,
                                                  1837970263,
                                                  1067644340,
                                                  523549916,
                                                  2119366659,
                                                  14,
                                              } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_e_to_one_half = { 1,
                                             6,
                                             0,
                                             {
                                                 256945612,
                                                 216219427,
                                                 223516738,
                                                 477442596,
                                                 581063757,
                                                 23,
                                             } };
inline const NUMBER init_q_e_to_one_half = { 1,
                                             6,
                                             0,
                                             {
                                                 1536828363,
                                                 698484484,
                                                 1127331835,
                                                 224219346,
                                                 245499408,
                                                 14,
                                             } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_exp = { 1,
                                       6,
                                       0,
                                       {
                                           943665199,
                                           1606559160,
                                           1094967530,
                                           1759391384,
                                           1671799163,
                                           1123581,
                                       } };
inline const NUMBER init_q_rat_exp = { 1,
                                       6,
                                       0,
                                       {
                                           879242208,
                                           2022880100,
                                           617392930,
                                           1374929092,
                                           1367479163,
                                           413342,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_ln_ten = { 1,
                                      6,
                                      0,
                                      {
                                          2086268922,
                                          165794492,
                                          1416063951,
                                          1851428830,
                                          1893239400,
                                          65366841,
                                      } };
inline const NUMBER init_q_ln_ten = { 1,
                                      6,
                                      0,
                                      {
                                          26790652,
                                          564532679,
                                          783998273,
                                          216030448,
                                          1564709968,
                                          28388458,
                                      } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_ln_two = { 1,
                                      6,
                                      0,
                                      {
                                          1789230241,
                                          1057927868,
                                          715399197,
                                          908801241,
                                          1411265331,
                                          3,
                                      } };
inline const NUMBER init_q_ln_two = { 1,
                                      6,
                                      0,
                                      {
                                          1559869847,
                                          1930657510,
                                          1228561531,
                                          219003871,
                                          593099283,
                                          5,
                                      } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rad_to_deg = { 1,
                                          6,
                                          0,
                                          {
                                              2127722024,
                                              1904928383,
                                              2016479213,
                                              2048947859,
                                              1578647346,
                                              492,
                                          } };
inline const NUMBER init_q_rad_to_deg = { 1,
                                          6,
                                          0,
                                          {
                                              125527896,
                                              283898350,
                                              1960493936,
                                              1672850762,
                                              1288168272,
                                              8,
                                          } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rad_to_grad = { 1,
                                           6,
                                           0,
                                           {
                                               2125526288,
                                               684931327,
                                               570267400,
                                               129125085,
                                               1038224725,
                                               547,
                                           } };
inline const NUMBER init_q_rad_to_grad = { 1,
                                           6,
                                           0,
                                           {
                                               125527896,
                                               283898350,
                                               1960493936,
                                               1672850762,
                                               1288168272,
                                               8,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_qword = { 1,
                                         3,
                                         0,
                                         {
                                             2147483647,
                                             2147483647,
                                             3,
                                         } };
inline const NUMBER init_q_rat_qword = { 1,
                                         1,
                                         0,
                                         {
                                             1,
                                         } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_dword = { 1,
                                         2,
                                         0,
                                         {
                                             2147483647,
                                             1,
                                         } };
inline const NUMBER init_q_rat_dword = { 1,
                                         1,
                                         0,
                                         {
                                             1,
                                         } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_max_i32 = { 1,
                                           1,
                                           0,
                                           {
                                               2147483647,
                                           } };
inline const NUMBER init_q_rat_max_i32 = { 1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_min_i32 = { -1,
                                           2,
                                           0,
                                           {
                                               0,
                                               1,
                                           } };
inline const NUMBER init_q_rat_min_i32 = { 1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_word = { 1,
                                        1,
                                        0,
                                        {
                                            65535,
                                        } };
inline const NUMBER init_q_rat_word = { 1,
                                        1,
                                        0,
                                        {
                                            1,
                                        } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_byte = { 1,
                                        1,
                                        0,
                                        {
                                            255,
                                        } };
inline const NUMBER init_q_rat_byte = { 1,
                                        1,
                                        0,
                                        {
                                            1,
                                        } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_400 = { 1,
                                       1,
                                       0,
                                       {
                                           400,
                                       } };
inline const NUMBER init_q_rat_400 = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_360 = { 1,
                                       1,
                                       0,
                                       {
                                           360,
                                       } };
inline const NUMBER init_q_rat_360 = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_200 = { 1,
                                       1,
                                       0,
                                       {
                                           200,
                                       } };
inline const NUMBER init_q_rat_200 = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_180 = { 1,
                                       1,
                                       0,
                                       {
                                           180,
                                       } };
inline const NUMBER init_q_rat_180 = { 1,
                                       1,
                                       0,
                                       {
                                           1,
                                       } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_max_exp = { 1,
                                           1,
                                           0,
                                           {
                                               100000,
                                           } };
inline const NUMBER init_q_rat_max_exp = { 1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };
// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_min_exp = { -1,
                                           1,
                                           0,
                                           {
                                               100000,
                                           } };
inline const NUMBER init_q_rat_min_exp = { 1,
                                           1,
                                           0,
                                           {
                                               1,
                                           } };

// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_max_fact = { 1,
                                            1,
                                            0,
                                            {
                                                3249,
                                            } };
inline const NUMBER init_q_rat_max_fact = { 1,
                                            1,
                                            0,
                                            {
                                                1,
                                            } };

// Autogenerated by _dumprawrat in support.cpp
inline const NUMBER init_p_rat_min_fact = { -1,
                                            1,
                                            0,
                                            {
                                                1000,
                                            } };
inline const NUMBER init_q_rat_min_fact = { 1,
                                            1,
                                            0,
                                            {
                                                1,
                                            } };
